WebApplication3/Models/Car.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication3.Models
{
    public class Car
    {
        public int VIN { get; set; }
        [PrimaryKey(nameof(VIN))]
        public string LicensePlate { get; set; }

        public string Make {  get; set; }

        public string Model { get; set; }

        public string Mileage { get; set; }

        public int OfficerID { get; set; }
        [ForeignKey("OfficerID")]
        public Officer? officer
        { get; set; }
    }
}

WebApplication3/Models/ErrorViewModel.cs
namespace WebApplication3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication3/Models/Officer.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplication3.Models
{
    public class Officer
    {
        public int OfficerID { get; set; }

        public string Name { get; set; }

        public string Address { get; set; }

        public string Phone { get; set; }

        public string DOB { get; set; }

        public string DriversLicenseNum { get; set; }
    }
}

WebApplication3/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Data;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class CarController : Controller
    {

        private CarsDbContext _dbContext;

        public CarController(CarsDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var listOfCars = _dbContext.Cars.ToList();
            return View(listOfCars);
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            Car car = _dbContext.Cars.Find(id);
                return View(car);
        }

        [HttpPost]
        public IActionResult Update(int id, [Bind("VIN, LicensePlate, Make, Model, Mileage, OfficerID")] Car Carobj) 
        { 
            if (ModelState.IsValid)
            {
                _dbContext.Cars.Update(Carobj);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(Carobj);
        }
    }
}

WebApplication3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using WebApplication3.Data;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        private CarsDbContext _dbContext;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, CarsDbContext carsDbContext)
        {
            _logger = logger;
            _dbContext = carsDbContext;
        }

        public IActionResult Index()
        {
            var listOfCars = _dbContext.Cars.Include(c => c.officer);
            return View(listOfCars.ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication3/Views/Car/Index.cshtml
@model List<Car>

<h1> Service request List </h1>


<div class="pt-2 pb-2">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>VIN</th>
                <th>License Plate</th>
                <th>Make</th>
                <th>Model</th>
                <th>Mileage</th>
                <th>Officer</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var eachCar in Model)
            {
                <tr>
                    <td>@eachCar.VIN</td>
                    <td>@eachCar.LicensePlate</td>
                    <td>@eachCar.Make</td>
                    <td>@eachCar.Model</td>
                    <td>@eachCar.Mileage</td>
                    <td>@eachCar.OfficerID</td>
                    <td>
                        <a asp-controller="Car" asp-action="Update" asp-route-id="@eachCar.VIN">Edit</a>
                        <a asp-controller="Car" asp-action="Delete" asp-route-id="@eachCar.VIN">Edit</a>
                        <a asp-controller="Car" asp-action="Details" asp-route-id="@eachCar.VIN">Edit</a>
                    </td>
                </tr>

            }

        </tbody>
    </table>

</div>

WebApplication3/Views/Car/update.cshtml
@model Car

<h1>Update Vehicle</h1>

<div class=" border col-md-10">
    <form asp-action="Update">

        <div class="form-group m-4">
            <label asp-for="VIN" class="control-label"></label>
            <input asp-for="VIN" class="form-control" />
        </div>

        <div class="form-group m-4">
            <label asp-for="LicensePlate" class="control-label"></label>
            <input asp-for="LicensePlate" class="form-control" />
        </div>

        <div class="form-group m-4">
            <label asp-for="Make" class="control-label"></label>
            <input asp-for="Make" class="form-control" />
        </div>

        <div class="form-group m-4">
            <label asp-for="Model" class="control-label"></label>
            <input asp-for="Model" class="form-control" />
        </div>
        <div class="form-group m-4">
            <label asp-for="Mileage" class="control-label"></label>
            <input asp-for="Mileage" class="form-control" />
        </div>
        <div class="form-group m-4">
            <label asp-for="OfficerID" class="control-label"></label>
            <input asp-for="OfficerID" class="form-control" />
        </div>

        <div class="form-group m-4">
            <input type="Submit" value="Save Changes" class="form-control btn btn-primary" />
        </div>
    </form>

</div>

WebApplication3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>